# Generated by Django 5.0.4 on 2024-06-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surtidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('saldo_gasolina', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saldo_gasolinapremium', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saldo_diesel', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
