# Generated by Django 5.0.4 on 2024-06-15 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasolina', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bomba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('surtidor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surtidor', to='gasolina.surtidor')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.IntegerField(blank=True, choices=[(1, 'Vendedor'), (2, 'Administrador')], null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_factura', models.CharField(max_length=255)),
                ('nit_factura', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_actual_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_producto_litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_producto', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('bomba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bomba', to='gasolina.bomba')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='gasolina.cliente')),
            ],
        ),
    ]
